Fixes

diff --git a/iob_node_update b/iob_node_update
--- a/iob_node_update
+++ b/iob_node_update
@@ -269,6 +269,12 @@ then
         exit;
 fi
 
+if [ NODERECOM != "" ]
+        then 
+        echo "Could not detect recommended nodejs-version. Please run 'iob node-update' again.";
+        exit 1;
+fi;
+
 if [[ "$VERNODE" != "v$NODERECOM" ]]
 then
         echo -e "\n!!! THIS CODE IS IN BETA STAGE. TRY IT AT YOUR OWN RISK !!!";
